### ISSUE TITLE
fit input PSFs w/ admom and flag them

### ISSUE THREAD

**Issue by beckermr** [beckermr/pizza-cutter#278]

**Comment by rmjarvis** [comment]
It seems that with color interpolation, there is more opportunity for parts of the CCD to require extrapolation beyond the support of the stars' positions and colors.  Especially since the colors of galaxies may be pretty different from the colors of stars (g-i ~ 0.6 compared to star ranging from 0 to 3).  If a slight outlier near the edge happens to have pretty different colors than other nearby stars, then the color term can be relatively large and extrapolation to g-i=0.6 can have bad artifacts.
Matt and I think that probably measuring adaptive moments of the stars on a grid at g-i=0.6 should show when this kind of problem is occurring, so either the whole CCD can be excluded, or maybe just limit the usable area to some central region where the fits look sane.
The exact heuristic to use for identifying this failure mode is still TBD. 
An example case in the test run where it happened is D00365160_r_c42_r5473p01_piff-model.fits.  The lower right corner has wonky images when drawn at g-i=0.6.  But everything above y=1000 looks pretty reasonable, so most of the CCD is potentially usable despite the failure in the corner.
