### ISSUE TITLE
separate medsconf from the download area for the SE images

### ISSUE THREAD

**Issue by beckermr** [beckermr/pizza-cutter#98]

**Comment by esheldon** [comment]
I forget what this issue is about.

We want to store the single epoch data and the meds file under $MEDS_DIR.

We will usually run the prep code with `--clean` after the meds file is made.

Currently we determine the name under $MEDS_DIR from the config file name.

Is the idea to separate medsconf from the file name?  Do you remember why @beckermr  ?

**Comment by beckermr** [comment]
I think we might want to make more than one meds filefrom a single set of SE data to test the image interpolation, coadding etc.

**Comment by esheldon** [comment]
I see.

Note that downloading the data takes a tiny fraction of the total time to make the meds file.

**Comment by beckermr** [comment]
fair - I am mostly worried about disk space

**Comment by esheldon** [comment]
We can run the prep code with `--clean` right after making the meds file

**Comment by beckermr** [comment]
Ok. Let’s close this until later.
